### ISSUE TITLE
Error running on Rakudo 2017.10

### ISSUE THREAD

**Issue by ghost** [ufobat/HTTP-Server-Ogre#2]
IO::Socket::Async::SSL is a builtin type, not an external module
  in method run at /usr/lib/perl6/perl6/site/sources/4544DCD8AF260C3DA224E3290A9B293D246C8A50 (HTTP::Server::Ogre) line 58

**Comment by ghost** [comment]
Some research showed it was a result of IO::Socket::Async::SSL not installed.
Not closing anyway as error message is dubious and thus either presence of required module  should be checked at runtime, or it should be included in dependencies.
BTW, thanks for the module, makes things much easier when starting to playing around with P6 concurrency.

**Comment by ufobat** [comment]
Thanks for the report. I am happy that you like my module :-)

IO::Socket::Async::SSL is not required to run HTTP::Server::Ogre, unless you want to use https. 

Assuming IO::Socket::Async::SSL would be part of the dependencies, it would be required to have some openssl-dev libraries installed on your system. Which is quite much, when you might want to do only http.

After some disscussion on IRC i've decided not to put IO::Socket::Async::SSL as a dependency into the META6.json. But, like you, I am unhappy about this.

But, the first error message

> IO::Socket::Async::SSL is a builtin type, not an external module

is wrong, isn't it. Is this a LTA error?

**Comment by ufobat** [comment]
https://irclog.perlgeek.de/perl6/2017-11-19#i_15468905
